source "https://rubygems.org"

gem "oj", "3.13.19"
gem "json", "2.6.2"
gem "async", "1.30.3"
gem "async-http", "0.59.2"
gem "fluentd", "1.15.2"
gem "fluent-plugin-azure-loganalytics", "0.7.0"
gem "fluent-plugin-azurestorage-gen2", "0.3.3"
gem "fluent-plugin-cloudwatch-logs", "0.14.3"
gem "fluent-plugin-concat", "2.5.0"
gem "fluent-plugin-datadog", "0.14.2"
gem "fluent-plugin-elasticsearch", "5.2.3"
gem "fluent-plugin-grafana-loki", "1.2.18"
gem "fluent-plugin-kafka", "0.18.1"
gem "fluent-plugin-opensearch", "1.0.8"
gem "fluent-plugin-prometheus", "2.0.3"
gem "fluent-plugin-record-modifier", "2.1.1"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-route", "1.0.0"
gem "fluent-plugin-s3", "1.7.1"
gem "fluent-plugin-sqs", "3.0.0"
