source "https://rubygems.org"

gem "libxml-ruby", "4.1.1"
gem "oj", "3.15.0"
gem "json", "2.6.3"
gem "async", "1.31.0"
gem "async-http", "0.60.1"
gem "fluentd", "1.16.1"
gem "fluent-plugin-azure-loganalytics", "0.7.0"
gem "fluent-plugin-azurestorage-gen2", "0.3.5"
gem "fluent-plugin-cloudwatch-logs", "0.14.3"
gem "fluent-plugin-concat", "2.5.0"
gem "fluent-plugin-datadog", "0.14.2"
gem "fluent-plugin-elasticsearch", "5.3.0"
gem "fluent-plugin-grafana-loki", "1.2.20"
gem "fluent-plugin-kafka", "0.19.0"
gem "fluent-plugin-opensearch", "1.1.0"
gem "fluent-plugin-prometheus", "2.0.3"
gem "fluent-plugin-record-modifier", "2.1.1"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-route", "1.0.0"
gem "fluent-plugin-s3", "1.7.2"
gem "fluent-plugin-sqs", "3.0.0"
