source "https://rubygems.org"

gem "libxml-ruby", "5.0.3"
gem "oj", "3.16.7"
gem "json", "2.8.2"
gem "async", "1.32.1"
gem "async-http", "0.64.2"
gem "fluentd", "1.17.1"
gem "fluent-plugin-azure-loganalytics", "0.7.0"
gem "fluent-plugin-azurestorage-gen2", "0.3.9"
gem "fluent-plugin-cloudwatch-logs", "0.14.3"
gem "fluent-plugin-concat", "2.5.0"
gem "fluent-plugin-datadog", "0.14.4"
gem "fluent-plugin-elasticsearch", "5.4.3"
gem "fluent-plugin-grafana-loki", "1.2.20"
gem "fluent-plugin-kafka", "0.19.3"
gem "fluent-plugin-opensearch", "1.1.5"
gem "fluent-plugin-prometheus", "2.2.0"
gem "fluent-plugin-record-modifier", "2.2.0"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-route", "1.0.0"
gem "fluent-plugin-s3", "1.8.1"
gem "fluent-plugin-sqs", "3.0.0"
