issuer: https://token.actions.githubusercontent.com
subject: repo:stevehipwell/fluentd-aggregator:pull_request
claim_pattern:
  base_ref: refs/heads/main
  actor: dependabot[bot]

permissions:
  contents: write
